project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

task/urls.py
from django.urls import path
from task import views

app_name = 'task'

urlpatterns = [
    path('<int:task_id>/', views.task, name='task'),
    path('', views.index, name='index'),
]

task/models.py
from django.db import models
from django.contrib.auth.models import User

# Filtros por usuário, status e data de vencimento.

class Task(models.Model):
    # ID - Primary key é criada automaticamente pelo django
    STATUS = [
        ('pendente', 'Pendente'),
        ('em andamento', 'Em andamento'),
        ('concluída', 'Concluída'),
    ]
    
    title = models.CharField(max_length=60)
    description = models.TextField(blank=True)
    deadline_date = models.DateField() # N SEI SE É ASSIM
    status = models.CharField(max_length=13, choices=STATUS, default='pendente') 
    
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tarefas_criadas', blank=True, null=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='atribuido_a', blank=True, null=True)
    
    def __str__(self):
        return f'{self.title}'

task/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request,
        'task/index.html',
    )

task/views/task_views.py
from django.shortcuts import render, get_object_or_404
from task.models import Task

def index(request):
    
    tasks = Task.objects.all()
    
    context = {
        'tasks': tasks,
    }
    
    return render(
        request,
        'task/index.html',
        context,
    )
    
def task(request, task_id):
    
    # single_tasks = Task.objects.get(id=task_id)
    single_task = get_object_or_404(Task, id=task_id)
    
    context = {
        'task': single_task,
    }
    
    return render(
        request,
        'task/task.html',
        context,
    )

task/templates/task/index.html
{% extends 'global/base.html' %}    

{% block content %}
    <div class="responsive">
        <table class="contacts-table">
            <caption class='table-caption'>
                Tarefas
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Tarefa</th>
                    <th class="table-header">Status</th>
                    <th class="table-header">Prazo</th>
                    <th class="table-header">Criado por</th>
                    <th class="table-header">Atribuido para</th>
                </tr>
            </thead>

            <tbody>
                {% for task in tasks %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a href="{% url "task:task" task.id %}" class="table-link">
                                {{task.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{task.title}}
                        </td>
                        <td class="table-cel">
                            {{task.status}}
                        </td>
                        <td class="table-cel">
                            {{task.deadline_date}}
                        </td>
                        <td class="table-cel">                        
                        {{task.created_by}}
                        </td>
                        <td class="table-cel">                        
                        {{task.assigned_to}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock content %}

task/templates/task/task.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            TAREFA: {{task.title}}
        </h1>
    </div>

    <p><b>ID:</b> {{task.id}}</p>
    <p><b>Tarefa:</b> {{task.title}}</p>
    <p><b>Status:</b> {{task.status}}</p>
    <p><b>Prazo:</b> {{task.deadline_date}}</p>
    <p><b>Descrição:</b> {{task.description}}</p>
    <p><b>Criado por:</b> {{task.created_by}}</p>
    <p><b>Atribuído à:</b> {{task.assigned_to}}</p>
    
{% endblock content %}